baseURL = "/"
languageCode = "en-us"
title = "Mason's History Topic Organizers"
theme = "digital-garden-hugo-theme"

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "My Digital Garden on the Internet"
  images = ['/digital-garden-logo.png']
  enableSearch = true


[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Other Assignments'
  url = '/articles'
  weight = 5
[[menu.main]]
  name = 'Topic Organizers'
  url = '/stack'
  weight = 4

[[menu.main]]
  name = 'Links'
  params.header = true
  weight = 6
[[menu.main]]
  name = 'Source Code'
  url = 'https://github.com/Mason-code/Mason-Neurauter-site/tree/master'
  weight = 7
[[menu.main]]
  name = 'National Geographic'
  url = 'https://www.nationalgeographic.com/'
  weight = 8
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/Mason-code'
  weight = 2

[[menu.social]]
  name = 'Email'
  url = 'mailto:mason.neurauter@gmail.com'
  weight = 8


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
